### ISSUE TITLE
January 28, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by sz16900** [Flakster/Flowers-shop-site#1]
Great starting this project with a good style. Looks like you are on to a great start! Keep up that good work.

**Comment by jabichris** [comment]
Nice work buddy. Even though the work is great, make sure before committing your code use the validator to check the errors. Other than that, happy coding buddy!

**Comment by Flakster** [comment]
Thanks for the feedback guys, I'll keep pushing!
