### ISSUE TITLE
February 2, 2020 | Code-Review : The Poodles  

### ISSUE THREAD

**Issue by sz16900** [Flakster/Flowers-shop-site#4]
Great job Carlos! Awesome website! Here is a quick heads-up:

- Please, do not forget to comment your code as much as possible. It's important to have more comments for outside people to quickly understand what is going on.

**Comment by Meltrust** [comment]
Beautiful site. Need to improve the readme but this is really pretty.

**Comment by kirokoNjenga** [comment]
### on the readme file:
- clearly explain what the web app is doing
- separate the web and mobile screen and if possible show for each three pages
- add your great moment on the project and clearly document it

**Comment by jabichris** [comment]
Nice work @Flakster, but as @Samkiroko said your Readme file can be improved.

**Comment by Flakster** [comment]
I already added more info to the README.md file as you guys suggested to me. Thanks for the feedback!
